spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/towako?characterEncoding=utf-8&useSSL=false
    username: root
    password: GAKqD8q8s/fbxM9YUiiMpaj0hYp1LuPCda0DkR/B3v/fXpra1vKP+9cBtrXTwYJrDweDnAsFuscHiP5C3XZ6DA==
    decrypt: true
    public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIdafBFEbA+F7zB0RcwPOFzGUSo5tB2ggQh2Ay0MlKjlt9oKFfIHDKzt9jim+mZHONZsgOUktccAb0nFYX4TlikCAwEAAQ==
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  flyway:
    clean-disabled: true
    locations: classpath:db/migration,classpath:db/dev.migration
    out-of-order: true
    table: schema_towako_version

  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /towako
    username: rabbitmqadmin
    password: 123456

  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 200ms # 连接超时时间（毫秒）

#cartisan:
#  signature:
#    enable: false
#    secret: cartisan

logging:
  file:
    #path: /var/log/towako/
    path: /Users/colin/logs/towako
    name: towako
