spring:
  datasource:
    url: jdbc:p6spy:mysql://172.17.16.4:3306/towako?characterEncoding=utf-8&useSSL=false
    username: root
    password: PZMcLU/NozpY7MRWjSqsCr+ZIp2L64o8Q/OIW2gxTloWfWrbQnRGgymMAkKgQ7I4DhW4dePesmDUA1MhdJjA8w==
    decrypt: true
    public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJGvnnJ5zDeTj01GwwgXxwMeaH9nYsFSmxMZScKBiW/Fbsxx2yna1wE5z771ik6BDVX3CqWdlqZhfwWvIrFgCR8CAwEAAQ==
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  flyway:
    clean-disabled: true
    locations: classpath:db/migration,classpath:db/prod.migration
    out-of-order: true
    table: schema_towako_version

#  rabbitmq:
#    host: localhost
#    port: 5672
#    virtual-host: /towako
#    username: rabbitmqadmin
#    password: 123456

  redis:
    host: 172.17.0.2 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: L@nmedic@1 # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 200ms # 连接超时时间（毫秒）

wx:
  mp:
    configs:
      - appId: wxf200906089a66e87 # 第一个公众号的appid
        secret: 2ac0d999bd43ca749f2ad0974ba09ed8 # 公众号的appsecret
        token: cartisan # 接口配置里的Token值
        aesKey: VNbqOjvckkvmy79O1ybmYZIagfNYW5aXilVuYjSlHwA
  miniapp:
    configs:
      - appid: wx200648b927810972 # 悦鲜坊appid
        secret: 0f1b97bbd981668dc4ba2c86277075b1 #微信小程序的Secret
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON
#      - appid: wx200648b927810972 # 原竹悦鲜坊appid
#        secret: cb9ec12aae533b712cbde5c08f8fae62 #微信小程序的Secret
#        token: #微信小程序消息服务器配置的token
#        aesKey: #微信小程序消息服务器配置的EncodingAESKey
#        msgDataFormat: JSON
logging:
  file:
    path: ./log/towako/
    name: towako
