server:
  port: 8080
#  servlet:
#    context-path: /towako

spring:
  application:
    name: towako
  profiles:
    include: web, mysql
    active: local

  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: service@lanmedical.com
    password: Y7HFWrfzfNnEyNnH
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            socketFactory:
              class: com.sun.mail.util.MailSSLSocketFactory
              fallback: false

cartisan:
  jwt:
    key: cartisan-jwt
    ttl: 1800000
  info:
    title: Towako 后台管理系统
    serviceUrl: http://www.cartisan.com
    version: 1.0
    contact:
      name: colin
      url: zhang_colin.github.com
      email: zhang_colin@163.com
  security:
    ignored:
      urls: # 安全路由白名单
        - /
        - /*.html
        - /**/*.html
        - /**/*.css
        - /**/*.js
        - /**/v2/api-docs/**
        - /**/v2/api-docs-ext/**
        - /**/*.png
        - /**/*.ico
        - /swagger-ui.html
        - /swagger-resources/**
        - /swagger/**
        - /webjars/springfox-swagger-ui/**
        - /actuator/**
        - /druid/**
        - /system/login
        - /mp/**
        - /traffic/mychannel/recommendPoster
        - /traffic/mychannel/qrcode
        - /traffic/mychannel/register
        - /captcha/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
