### 获取所有菜单
GET http://{{host}}:{{port}}/system/menus
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 添加菜单
POST http://{{host}}:{{port}}/system/menus
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  "title": "系统管理",
  "parentId": 0,
  "name": "system",
  "icon": "",
  "hidden": false,
  "sort": 1
}

### 编辑菜单
PUT http://{{host}}:{{port}}/system/menus/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  "title": "系统管理-1",
  "parentId": 0,
  "name": "system-1",
  "icon": "",
  "hidden": false,
  "sort": 1
}

### 删除菜单
DELETE http://{{host}}:{{port}}/system/menus/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

###